# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration
  config.vm.box = "ubuntu/bionic64"

  # Spectre Web configuration
  config.vm.define "spectre_web" do |web|
    web.vm.hostname = "spectre-web"
    web.vm.network "private_network", ip: "192.168.56.101"
    web.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh"
    web.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/application1_playbook.yml"
    end
  end

  # Spectre API configuration
  config.vm.define "spectre_api" do |api|
    api.vm.hostname = "spectre-api"
    api.vm.network "private_network", ip: "192.168.56.102"
    api.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"
    api.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    api.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/application2_playbook.yml"
    end
  end

  # Spectre Android configuration
  config.vm.define "spectre_android" do |android|
    android.vm.hostname = "spectre-android"
    android.vm.network "private_network", ip: "192.168.56.103"
    android.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"
    android.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    android.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/application3_playbook.yml"
    end
  end
end
